### ISSUE TITLE
Some organizations block docs.google.com, therefore it is impossible to access your presentations

### ISSUE THREAD

**Issue by slamont** [teivah/talks#1]
Hi,

I was at ConFoo 2024 this week and I really enjoyed your talk on reliability. I was glad to see the link for the slides and was going to create a nice summary in our company's internal Wiki to spread the knowledge and link to them. Unfortunately, company policies block docs.google.com. Would it be possible to make your talk available as a PDF ?

Thank You

**Comment by teivah** [comment]
Hey @slamont,

Thanks, glad you enjoyed it :)

Here it is: https://github.com/teivah/talks/blob/master/README.md#4-reliability-anti-patterns-confoo-2024-conference
